# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RockPaperScissorsQt.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(585, 429)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 170, 350, 110))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.rockButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.rockButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setKerning(True)
        self.rockButton.setFont(font)
        self.rockButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("images/rock.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rockButton.setIcon(icon)
        self.rockButton.setIconSize(QtCore.QSize(100, 100))
        self.rockButton.setObjectName(_fromUtf8("rockButton"))
        self.horizontalLayout.addWidget(self.rockButton)
        self.paperButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.paperButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("images/paper.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.paperButton.setIcon(icon1)
        self.paperButton.setIconSize(QtCore.QSize(100, 100))
        self.paperButton.setObjectName(_fromUtf8("paperButton"))
        self.horizontalLayout.addWidget(self.paperButton)
        self.scissorsButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.scissorsButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scissorsButton.sizePolicy().hasHeightForWidth())
        self.scissorsButton.setSizePolicy(sizePolicy)
        self.scissorsButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scissorsButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("images/scissors.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scissorsButton.setIcon(icon2)
        self.scissorsButton.setIconSize(QtCore.QSize(100, 100))
        self.scissorsButton.setAutoDefault(False)
        self.scissorsButton.setDefault(False)
        self.scissorsButton.setObjectName(_fromUtf8("scissorsButton"))
        self.horizontalLayout.addWidget(self.scissorsButton)
        self.yourScoreLabel = QtGui.QLabel(self.centralwidget)
        self.yourScoreLabel.setGeometry(QtCore.QRect(390, 170, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.yourScoreLabel.setFont(font)
        self.yourScoreLabel.setObjectName(_fromUtf8("yourScoreLabel"))
        self.computerScoreLabel = QtGui.QLabel(self.centralwidget)
        self.computerScoreLabel.setGeometry(QtCore.QRect(390, 20, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.computerScoreLabel.setFont(font)
        self.computerScoreLabel.setObjectName(_fromUtf8("computerScoreLabel"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 140, 101, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 20, 332, 111))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.computerChoiceLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.computerChoiceLayout.setObjectName(_fromUtf8("computerChoiceLayout"))
        self.rockImage = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.rockImage.setEnabled(True)
        self.rockImage.setMaximumSize(QtCore.QSize(100, 100))
        self.rockImage.setInputMethodHints(QtCore.Qt.ImhNone)
        self.rockImage.setText(_fromUtf8(""))
        self.rockImage.setPixmap(QtGui.QPixmap(_fromUtf8("images/rock.png")))
        self.rockImage.setScaledContents(True)
        self.rockImage.setObjectName(_fromUtf8("rockImage"))
        self.computerChoiceLayout.addWidget(self.rockImage)
        self.paperImage = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.paperImage.setMaximumSize(QtCore.QSize(100, 100))
        self.paperImage.setText(_fromUtf8(""))
        self.paperImage.setPixmap(QtGui.QPixmap(_fromUtf8("images/paper.png")))
        self.paperImage.setScaledContents(True)
        self.paperImage.setObjectName(_fromUtf8("paperImage"))
        self.computerChoiceLayout.addWidget(self.paperImage)
        self.scissorsImage = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.scissorsImage.setMaximumSize(QtCore.QSize(100, 100))
        self.scissorsImage.setText(_fromUtf8(""))
        self.scissorsImage.setPixmap(QtGui.QPixmap(_fromUtf8("images/scissors.png")))
        self.scissorsImage.setScaledContents(True)
        self.scissorsImage.setObjectName(_fromUtf8("scissorsImage"))
        self.computerChoiceLayout.addWidget(self.scissorsImage)
        self.yourScore = QtGui.QLabel(self.centralwidget)
        self.yourScore.setGeometry(QtCore.QRect(510, 170, 47, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.yourScore.setFont(font)
        self.yourScore.setObjectName(_fromUtf8("yourScore"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 0, 101, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.computerScore = QtGui.QLabel(self.centralwidget)
        self.computerScore.setGeometry(QtCore.QRect(510, 20, 47, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.computerScore.setFont(font)
        self.computerScore.setObjectName(_fromUtf8("computerScore"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 585, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuGra = QtGui.QMenu(self.menubar)
        self.menuGra.setObjectName(_fromUtf8("menuGra"))
        self.menuPomoc = QtGui.QMenu(self.menubar)
        self.menuPomoc.setObjectName(_fromUtf8("menuPomoc"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionNewGame = QtGui.QAction(MainWindow)
        self.actionNewGame.setObjectName(_fromUtf8("actionNewGame"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.menuGra.addAction(self.actionNewGame)
        self.menuGra.addAction(self.actionExit)
        self.menuPomoc.addAction(self.actionHelp)
        self.menubar.addAction(self.menuGra.menuAction())
        self.menubar.addAction(self.menuPomoc.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Kamień, Papier, Nożyce", None))
        self.rockButton.setToolTip(_translate("MainWindow", "Kamień", None))
        self.rockButton.setShortcut(_translate("MainWindow", "1", None))
        self.paperButton.setToolTip(_translate("MainWindow", "Papier", None))
        self.paperButton.setShortcut(_translate("MainWindow", "2", None))
        self.scissorsButton.setToolTip(_translate("MainWindow", "Nożyce", None))
        self.scissorsButton.setShortcut(_translate("MainWindow", "3", None))
        self.yourScoreLabel.setText(_translate("MainWindow", "Twój wynik: ", None))
        self.computerScoreLabel.setText(_translate("MainWindow", "Komputer:", None))
        self.label.setText(_translate("MainWindow", "Wybierz symbol:", None))
        self.rockImage.setToolTip(_translate("MainWindow", "Kamień", None))
        self.paperImage.setToolTip(_translate("MainWindow", "Papier", None))
        self.scissorsImage.setToolTip(_translate("MainWindow", "Nożyce", None))
        self.yourScore.setText(_translate("MainWindow", "0", None))
        self.label_2.setText(_translate("MainWindow", "Przeciwnik:", None))
        self.computerScore.setText(_translate("MainWindow", "0", None))
        self.menuGra.setTitle(_translate("MainWindow", "Gra", None))
        self.menuPomoc.setTitle(_translate("MainWindow", "Pomoc", None))
        self.actionNewGame.setText(_translate("MainWindow", "Nowa", None))
        self.actionNewGame.setShortcut(_translate("MainWindow", "N", None))
        self.actionExit.setText(_translate("MainWindow", "Zakończ", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Q", None))
        self.actionHelp.setText(_translate("MainWindow", "Zasady gry", None))
        self.actionHelp.setShortcut(_translate("MainWindow", "H", None))

